/**
 * Server Action Types — vendor-neutral constants for all admin actions.
 *
 * No file outside of server-actions/providers/ should reference CFCloud_*
 * action codes or any other vendor-specific identifiers.
 */

// ─── Action Type Constants ──────────────────────────────
const ActionType = Object.freeze({
  // Player actions — basic
  HEAL_PLAYER:           'player.heal',
  KILL_PLAYER:           'player.kill',
  TELEPORT_PLAYER:       'player.teleport',
  SPAWN_ITEM:            'player.spawnItem',
  STRIP_PLAYER:          'player.strip',
  EXPLODE_PLAYER:        'player.explode',
  MESSAGE_PLAYER:        'player.message',
  KICK_PLAYER:           'player.kick',
  BAN_PLAYER:            'player.ban',
  UNSTUCK_PLAYER:        'player.unstuck',
  FREEZE_PLAYER:         'player.freeze',
  TELEPORT_TO_PLAYER:    'player.teleportToPlayer',
  GET_LOADOUT:           'player.getLoadout',

  // Player actions — health/status
  DRY_PLAYER:            'player.dry',
  BREAK_LEGS:            'player.breakLegs',
  MAKE_SICK:             'player.makeSick',
  CURE_PLAYER:           'player.cure',
  SET_BLOOD_TYPE:        'player.setBloodType',
  FORCE_DRINK:           'player.forceDrink',
  FORCE_EAT:             'player.forceEat',
  KNOCKOUT_PLAYER:       'player.knockout',
  WAKE_PLAYER:           'player.wake',
  SET_BLEEDING:          'player.setBleeding',
  STOP_BLEEDING:         'player.stopBleeding',

  // Player actions — ability/state
  DROP_GEAR:             'player.dropGear',
  LAUNCH_PLAYER:         'player.launch',
  SET_STAT:              'player.setStat',
  RAGDOLL_PLAYER:        'player.ragdoll',
  SET_GODMODE:           'player.setGodmode',
  REMOVE_GODMODE:        'player.removeGodmode',
  SET_INVISIBLE:         'player.setInvisible',
  REMOVE_INVISIBLE:      'player.removeInvisible',
  SET_STAMINA_INFINITE:  'player.setStaminaInfinite',
  REMOVE_STAMINA_INFINITE: 'player.removeStaminaInfinite',
  RESPAWN_PLAYER:        'player.respawn',
  CLEAR_INVENTORY:       'player.clearInventory',
  FILL_MAGAZINES:        'player.fillMagazines',

  // Vehicle actions
  DELETE_VEHICLE:        'vehicle.delete',
  REPAIR_VEHICLE:        'vehicle.repair',
  REFUEL_VEHICLE:        'vehicle.refuel',
  UNSTUCK_VEHICLE:       'vehicle.unstuck',
  EXPLODE_VEHICLE:       'vehicle.explode',
  KILL_ENGINE:           'vehicle.killEngine',
  EJECT_DRIVER:          'vehicle.ejectDriver',
  TELEPORT_VEHICLE:      'vehicle.teleport',

  // World actions
  SET_TIME:              'world.setTime',
  SET_WEATHER:           'world.setWeather',
  CLEAR_WEATHER:         'world.sunny',
  WIPE_AI:               'world.wipeAI',
  WIPE_VEHICLES:         'world.wipeVehicles',
  SPAWN_ITEM_WORLD:      'world.spawnItemWorld',
  SET_FOG:               'world.setFog',
  SET_WIND:              'world.setWind',
  FLATTEN_TREES:         'world.flattenTrees',
  CLEAR_ZOMBIES:         'world.clearZombies',
  DELETE_OBJECTS_RADIUS:  'world.deleteObjectsRadius',

  // Spawn actions — creatures/objects
  SPAWN_ZOMBIE:          'spawn.zombie',
  SPAWN_ANIMAL:          'spawn.animal',
  SPAWN_VEHICLE:         'spawn.vehicle',
  SPAWN_BUILDING:        'spawn.building',
  SPAWN_HORDE:           'spawn.horde',
  SPAWN_SUPPLY_CRATE:    'spawn.supplyCrate',
  SPAWN_LOOT_PILE:       'spawn.lootPile',
  SPAWN_ITEM_ATTACHED:   'spawn.itemAttached',
  SPAWN_ITEM_AT:         'spawn.itemAt',
  SPAWN_ZOMBIE_AT:       'spawn.zombieAt',
  SPAWN_ANIMAL_AT:       'spawn.animalAt',
  SPAWN_FIRE:            'spawn.fire',
  SPAWN_SMOKE:           'spawn.smoke',
  SPAWN_HELI_CRASH:      'spawn.heliCrash',
  SPAWN_GAS_ZONE:        'spawn.gasZone',

  // Structure actions
  OPEN_DOORS:            'structure.openDoors',
  CLOSE_DOORS:           'structure.closeDoors',
  LOOT_MAGNET:           'structure.lootMagnet',

  // Item actions
  DELETE_ITEM:           'item.delete',
  REPAIR_ITEM:           'item.repair',

  // Server/config actions
  RELOAD_CONFIG:         'config.reload',

  // Data / query actions
  GET_PLAYER_DETAILS:    'data.playerDetails',
  GET_CAPABILITIES:      'data.capabilities',
  GET_PLAYER_POSITION:   'data.playerPosition',
  GET_PLAYER_INFO:       'data.playerInfo',
  GET_ONLINE_PLAYERS:    'data.onlinePlayers',
  GET_ALL_PLAYERS:       'data.allPlayers',
  GET_PLAYER_GEAR:       'data.playerGear',
  GET_PLAYER_INVENTORY:  'data.playerInventory',
  GET_PLAYER_STATS:      'data.playerStats',
  GET_PLAYER_FULL:       'data.playerFull',
  GET_PLAYER_GEAR_FULL:  'data.playerGearFull',
  GET_PLAYER_HANDS_DATA: 'data.playerHandsData',
  GET_NEARBY_VEHICLES:   'data.nearbyVehicles',
  GET_VEHICLE_INFO:      'data.vehicleInfo',
  GET_ITEM_DETAILS:      'data.itemDetails',
  GET_SERVER_INFO:        'data.serverInfo',
  GET_BASE_OBJECTS:       'data.baseObjects',
  GET_STORAGE_CONTENTS:   'data.storageContents',
  GET_ALL_STORAGE_OBJECTS: 'data.allStorageObjects',
  GET_NEARBY_PLAYERS:     'data.nearbyPlayers',
  GET_NEARBY_LOOT:        'data.nearbyLoot',
  GET_NEARBY_ENTITIES:    'data.nearbyEntities',
  GET_NEARBY_ENTITIES_AT: 'data.nearbyEntitiesAt',
  GET_NEARBY_LOOT_AT:     'data.nearbyLootAt',
  UNBAN_PLAYER:           'data.unbanPlayer',
  GET_BANS:               'data.getBans',
});

// ─── Capability Sets ────────────────────────────────────
// Which actions each provider type can handle.

const LEGACY_SDK_CAPABILITIES = new Set([
  ActionType.HEAL_PLAYER,
  ActionType.KILL_PLAYER,
  ActionType.TELEPORT_PLAYER,
  ActionType.SPAWN_ITEM,
  ActionType.STRIP_PLAYER,
  ActionType.EXPLODE_PLAYER,
  ActionType.MESSAGE_PLAYER,
  ActionType.KICK_PLAYER,
  ActionType.BAN_PLAYER,
  ActionType.DELETE_VEHICLE,
  ActionType.REPAIR_VEHICLE,
  ActionType.REFUEL_VEHICLE,
  ActionType.UNSTUCK_VEHICLE,
  ActionType.EXPLODE_VEHICLE,
  ActionType.KILL_ENGINE,
  ActionType.EJECT_DRIVER,
  ActionType.SET_TIME,
  ActionType.SET_WEATHER,
  ActionType.CLEAR_WEATHER,
  ActionType.WIPE_AI,
  ActionType.WIPE_VEHICLES,
  ActionType.SPAWN_ITEM_WORLD,
  ActionType.GET_PLAYER_DETAILS,
]);

const INHOUSE_CAPABILITIES = new Set([
  // Player — basic
  ActionType.HEAL_PLAYER,
  ActionType.KILL_PLAYER,
  ActionType.TELEPORT_PLAYER,
  ActionType.SPAWN_ITEM,
  ActionType.STRIP_PLAYER,
  ActionType.EXPLODE_PLAYER,
  ActionType.MESSAGE_PLAYER,
  ActionType.KICK_PLAYER,
  ActionType.BAN_PLAYER,
  ActionType.UNSTUCK_PLAYER,
  ActionType.FREEZE_PLAYER,
  ActionType.TELEPORT_TO_PLAYER,
  ActionType.GET_LOADOUT,
  // Player — health/status
  ActionType.DRY_PLAYER,
  ActionType.BREAK_LEGS,
  ActionType.MAKE_SICK,
  ActionType.CURE_PLAYER,
  ActionType.SET_BLOOD_TYPE,
  ActionType.FORCE_DRINK,
  ActionType.FORCE_EAT,
  ActionType.KNOCKOUT_PLAYER,
  ActionType.WAKE_PLAYER,
  ActionType.SET_BLEEDING,
  ActionType.STOP_BLEEDING,
  // Player — ability/state
  ActionType.DROP_GEAR,
  ActionType.LAUNCH_PLAYER,
  ActionType.SET_STAT,
  ActionType.RAGDOLL_PLAYER,
  ActionType.SET_GODMODE,
  ActionType.REMOVE_GODMODE,
  ActionType.SET_INVISIBLE,
  ActionType.REMOVE_INVISIBLE,
  ActionType.SET_STAMINA_INFINITE,
  ActionType.REMOVE_STAMINA_INFINITE,
  ActionType.RESPAWN_PLAYER,
  ActionType.CLEAR_INVENTORY,
  ActionType.FILL_MAGAZINES,
  // Vehicle
  ActionType.DELETE_VEHICLE,
  ActionType.REPAIR_VEHICLE,
  ActionType.REFUEL_VEHICLE,
  ActionType.UNSTUCK_VEHICLE,
  ActionType.EXPLODE_VEHICLE,
  ActionType.KILL_ENGINE,
  ActionType.EJECT_DRIVER,
  ActionType.TELEPORT_VEHICLE,
  // World
  ActionType.SET_TIME,
  ActionType.SET_WEATHER,
  ActionType.CLEAR_WEATHER,
  ActionType.WIPE_AI,
  ActionType.WIPE_VEHICLES,
  ActionType.SPAWN_ITEM_WORLD,
  ActionType.SET_FOG,
  ActionType.SET_WIND,
  ActionType.FLATTEN_TREES,
  ActionType.CLEAR_ZOMBIES,
  ActionType.DELETE_OBJECTS_RADIUS,
  // Spawn
  ActionType.SPAWN_ZOMBIE,
  ActionType.SPAWN_ANIMAL,
  ActionType.SPAWN_VEHICLE,
  ActionType.SPAWN_BUILDING,
  ActionType.SPAWN_HORDE,
  ActionType.SPAWN_SUPPLY_CRATE,
  ActionType.SPAWN_LOOT_PILE,
  ActionType.SPAWN_ITEM_ATTACHED,
  ActionType.SPAWN_ITEM_AT,
  ActionType.SPAWN_ZOMBIE_AT,
  ActionType.SPAWN_ANIMAL_AT,
  ActionType.SPAWN_FIRE,
  ActionType.SPAWN_SMOKE,
  ActionType.SPAWN_HELI_CRASH,
  ActionType.SPAWN_GAS_ZONE,
  // Structure
  ActionType.OPEN_DOORS,
  ActionType.CLOSE_DOORS,
  ActionType.LOOT_MAGNET,
  // Item
  ActionType.DELETE_ITEM,
  ActionType.REPAIR_ITEM,
  // Config
  ActionType.RELOAD_CONFIG,
  // Data / query
  ActionType.GET_PLAYER_DETAILS,
  ActionType.GET_PLAYER_POSITION,
  ActionType.GET_PLAYER_INFO,
  ActionType.GET_ONLINE_PLAYERS,
  ActionType.GET_ALL_PLAYERS,
  ActionType.GET_PLAYER_GEAR,
  ActionType.GET_PLAYER_INVENTORY,
  ActionType.GET_PLAYER_STATS,
  ActionType.GET_PLAYER_FULL,
  ActionType.GET_PLAYER_GEAR_FULL,
  ActionType.GET_PLAYER_HANDS_DATA,
  ActionType.GET_NEARBY_VEHICLES,
  ActionType.GET_VEHICLE_INFO,
  ActionType.GET_ITEM_DETAILS,
  ActionType.GET_SERVER_INFO,
  ActionType.GET_BASE_OBJECTS,
  ActionType.GET_STORAGE_CONTENTS,
  ActionType.GET_ALL_STORAGE_OBJECTS,
  ActionType.GET_NEARBY_PLAYERS,
  ActionType.GET_NEARBY_LOOT,
  ActionType.GET_NEARBY_ENTITIES,
  ActionType.GET_NEARBY_ENTITIES_AT,
  ActionType.GET_NEARBY_LOOT_AT,
  ActionType.UNBAN_PLAYER,
  ActionType.GET_BANS,
]);

const RCON_CAPABILITIES = new Set([
  ActionType.KICK_PLAYER,
  ActionType.BAN_PLAYER,
]);

// ─── Human-readable Names ───────────────────────────────
const ACTION_LABELS = Object.freeze({
  // Player — basic
  [ActionType.HEAL_PLAYER]:        'Heal Player',
  [ActionType.KILL_PLAYER]:        'Kill Player',
  [ActionType.TELEPORT_PLAYER]:    'Teleport Player',
  [ActionType.SPAWN_ITEM]:         'Spawn Item',
  [ActionType.STRIP_PLAYER]:       'Strip Inventory',
  [ActionType.EXPLODE_PLAYER]:     'Explode Player',
  [ActionType.MESSAGE_PLAYER]:     'Message Player',
  [ActionType.KICK_PLAYER]:        'Kick Player',
  [ActionType.BAN_PLAYER]:         'Ban Player',
  [ActionType.UNSTUCK_PLAYER]:     'Unstuck Player',
  [ActionType.FREEZE_PLAYER]:      'Freeze Player',
  [ActionType.TELEPORT_TO_PLAYER]: 'Teleport to Player',
  [ActionType.GET_LOADOUT]:        'Get Loadout',
  // Player — health/status
  [ActionType.DRY_PLAYER]:         'Dry Player',
  [ActionType.BREAK_LEGS]:         'Break Legs',
  [ActionType.MAKE_SICK]:          'Make Sick',
  [ActionType.CURE_PLAYER]:        'Cure Player',
  [ActionType.SET_BLOOD_TYPE]:     'Set Blood Type',
  [ActionType.FORCE_DRINK]:        'Force Drink',
  [ActionType.FORCE_EAT]:          'Force Eat',
  [ActionType.KNOCKOUT_PLAYER]:    'Knockout Player',
  [ActionType.WAKE_PLAYER]:        'Wake Player',
  [ActionType.SET_BLEEDING]:       'Set Bleeding',
  [ActionType.STOP_BLEEDING]:      'Stop Bleeding',
  // Player — ability/state
  [ActionType.DROP_GEAR]:          'Drop Gear',
  [ActionType.LAUNCH_PLAYER]:      'Launch Player',
  [ActionType.SET_STAT]:           'Set Player Stat',
  [ActionType.RAGDOLL_PLAYER]:     'Ragdoll Player',
  [ActionType.SET_GODMODE]:        'Enable God Mode',
  [ActionType.REMOVE_GODMODE]:     'Disable God Mode',
  [ActionType.SET_INVISIBLE]:      'Set Invisible',
  [ActionType.REMOVE_INVISIBLE]:   'Remove Invisible',
  [ActionType.SET_STAMINA_INFINITE]: 'Infinite Stamina',
  [ActionType.REMOVE_STAMINA_INFINITE]: 'Remove Infinite Stamina',
  [ActionType.RESPAWN_PLAYER]:     'Respawn Player',
  [ActionType.CLEAR_INVENTORY]:    'Clear Inventory',
  [ActionType.FILL_MAGAZINES]:     'Fill Magazines',
  // Vehicle
  [ActionType.DELETE_VEHICLE]:     'Delete Vehicle',
  [ActionType.REPAIR_VEHICLE]:     'Repair Vehicle',
  [ActionType.REFUEL_VEHICLE]:     'Refuel Vehicle',
  [ActionType.UNSTUCK_VEHICLE]:    'Unstuck Vehicle',
  [ActionType.EXPLODE_VEHICLE]:    'Explode Vehicle',
  [ActionType.KILL_ENGINE]:        'Kill Engine',
  [ActionType.EJECT_DRIVER]:       'Eject Driver',
  [ActionType.TELEPORT_VEHICLE]:   'Teleport Vehicle',
  // World
  [ActionType.SET_TIME]:           'Set Time',
  [ActionType.SET_WEATHER]:        'Set Weather',
  [ActionType.CLEAR_WEATHER]:      'Clear Weather (Sunny)',
  [ActionType.WIPE_AI]:            'Wipe AI',
  [ActionType.WIPE_VEHICLES]:      'Wipe Vehicles',
  [ActionType.SPAWN_ITEM_WORLD]:   'Spawn Item at Position',
  [ActionType.SET_FOG]:            'Set Fog',
  [ActionType.SET_WIND]:           'Set Wind',
  [ActionType.FLATTEN_TREES]:      'Flatten Trees',
  [ActionType.CLEAR_ZOMBIES]:      'Clear Zombies',
  [ActionType.DELETE_OBJECTS_RADIUS]: 'Delete Objects in Radius',
  // Spawn
  [ActionType.SPAWN_ZOMBIE]:       'Spawn Zombie',
  [ActionType.SPAWN_ANIMAL]:       'Spawn Animal',
  [ActionType.SPAWN_VEHICLE]:      'Spawn Vehicle',
  [ActionType.SPAWN_BUILDING]:     'Spawn Building',
  [ActionType.SPAWN_HORDE]:        'Spawn Horde',
  [ActionType.SPAWN_SUPPLY_CRATE]: 'Spawn Supply Crate',
  [ActionType.SPAWN_LOOT_PILE]:    'Spawn Loot Pile',
  [ActionType.SPAWN_ITEM_ATTACHED]: 'Spawn Item Attached',
  [ActionType.SPAWN_ITEM_AT]:      'Spawn Item at Position',
  [ActionType.SPAWN_ZOMBIE_AT]:    'Spawn Zombie at Position',
  [ActionType.SPAWN_ANIMAL_AT]:    'Spawn Animal at Position',
  [ActionType.SPAWN_FIRE]:         'Spawn Fire',
  [ActionType.SPAWN_SMOKE]:        'Spawn Smoke',
  [ActionType.SPAWN_HELI_CRASH]:   'Spawn Heli Crash',
  [ActionType.SPAWN_GAS_ZONE]:     'Spawn Gas Zone',
  // Structure
  [ActionType.OPEN_DOORS]:         'Open Doors',
  [ActionType.CLOSE_DOORS]:        'Close Doors',
  [ActionType.LOOT_MAGNET]:        'Loot Magnet',
  // Item
  [ActionType.DELETE_ITEM]:        'Delete Item',
  [ActionType.REPAIR_ITEM]:        'Repair Item',
  // Config
  [ActionType.RELOAD_CONFIG]:      'Reload Config',
  // Data / query
  [ActionType.GET_PLAYER_DETAILS]: 'Get Player Details',
  [ActionType.GET_PLAYER_POSITION]: 'Get Player Position',
  [ActionType.GET_PLAYER_INFO]:    'Get Player Info',
  [ActionType.GET_ONLINE_PLAYERS]: 'Get Online Players',
  [ActionType.GET_ALL_PLAYERS]:    'Get All Players',
  [ActionType.GET_PLAYER_GEAR]:    'Get Player Gear',
  [ActionType.GET_PLAYER_INVENTORY]: 'Get Player Inventory',
  [ActionType.GET_PLAYER_STATS]:   'Get Player Stats',
  [ActionType.GET_PLAYER_FULL]:    'Get Full Player Data',
  [ActionType.GET_PLAYER_GEAR_FULL]: 'Get Full Gear Data',
  [ActionType.GET_PLAYER_HANDS_DATA]: 'Get Hands Data',
  [ActionType.GET_NEARBY_VEHICLES]: 'Get Nearby Vehicles',
  [ActionType.GET_VEHICLE_INFO]:   'Get Vehicle Info',
  [ActionType.GET_ITEM_DETAILS]:   'Get Item Details',
  [ActionType.GET_SERVER_INFO]:    'Get Server Info',
  [ActionType.GET_BASE_OBJECTS]:   'Get Base Objects',
  [ActionType.GET_STORAGE_CONTENTS]: 'Get Storage Contents',
  [ActionType.GET_ALL_STORAGE_OBJECTS]: 'Get All Storage Objects',
  [ActionType.GET_NEARBY_PLAYERS]: 'Get Nearby Players',
  [ActionType.GET_NEARBY_LOOT]:    'Get Nearby Loot',
  [ActionType.GET_NEARBY_ENTITIES]: 'Get Nearby Entities',
  [ActionType.GET_NEARBY_ENTITIES_AT]: 'Get Nearby Entities at Position',
  [ActionType.GET_NEARBY_LOOT_AT]: 'Get Nearby Loot at Position',
  [ActionType.UNBAN_PLAYER]:       'Unban Player',
  [ActionType.GET_BANS]:           'Get Ban List',
});

// ─── Audit Code Map ─────────────────────────────────────
// Maps ActionType → audit log code
const AUDIT_CODES = Object.freeze({
  // Player — basic
  [ActionType.HEAL_PLAYER]:        'action.heal',
  [ActionType.KILL_PLAYER]:        'action.kill',
  [ActionType.TELEPORT_PLAYER]:    'action.teleport',
  [ActionType.SPAWN_ITEM]:         'action.spawn',
  [ActionType.STRIP_PLAYER]:       'action.strip',
  [ActionType.EXPLODE_PLAYER]:     'action.explode',
  [ActionType.MESSAGE_PLAYER]:     'action.message',
  [ActionType.KICK_PLAYER]:        'action.kick',
  [ActionType.BAN_PLAYER]:         'action.ban',
  [ActionType.UNSTUCK_PLAYER]:     'action.unstuck',
  [ActionType.FREEZE_PLAYER]:      'action.freeze',
  [ActionType.TELEPORT_TO_PLAYER]: 'action.teleportToPlayer',
  [ActionType.GET_LOADOUT]:        'action.getLoadout',
  // Player — health/status
  [ActionType.DRY_PLAYER]:         'action.dry',
  [ActionType.BREAK_LEGS]:         'action.breakLegs',
  [ActionType.MAKE_SICK]:          'action.makeSick',
  [ActionType.CURE_PLAYER]:        'action.cure',
  [ActionType.SET_BLOOD_TYPE]:     'action.setBloodType',
  [ActionType.FORCE_DRINK]:        'action.forceDrink',
  [ActionType.FORCE_EAT]:          'action.forceEat',
  [ActionType.KNOCKOUT_PLAYER]:    'action.knockout',
  [ActionType.WAKE_PLAYER]:        'action.wake',
  [ActionType.SET_BLEEDING]:       'action.setBleeding',
  [ActionType.STOP_BLEEDING]:      'action.stopBleeding',
  // Player — ability/state
  [ActionType.DROP_GEAR]:          'action.dropGear',
  [ActionType.LAUNCH_PLAYER]:      'action.launch',
  [ActionType.SET_STAT]:           'action.setStat',
  [ActionType.RAGDOLL_PLAYER]:     'action.ragdoll',
  [ActionType.SET_GODMODE]:        'action.setGodmode',
  [ActionType.REMOVE_GODMODE]:     'action.removeGodmode',
  [ActionType.SET_INVISIBLE]:      'action.setInvisible',
  [ActionType.REMOVE_INVISIBLE]:   'action.removeInvisible',
  [ActionType.SET_STAMINA_INFINITE]: 'action.setStaminaInfinite',
  [ActionType.REMOVE_STAMINA_INFINITE]: 'action.removeStaminaInfinite',
  [ActionType.RESPAWN_PLAYER]:     'action.respawn',
  [ActionType.CLEAR_INVENTORY]:    'action.clearInventory',
  [ActionType.FILL_MAGAZINES]:     'action.fillMagazines',
  // Vehicle
  [ActionType.DELETE_VEHICLE]:     'action.vehicle.delete',
  [ActionType.REPAIR_VEHICLE]:     'action.vehicle.repair',
  [ActionType.REFUEL_VEHICLE]:     'action.vehicle.refuel',
  [ActionType.UNSTUCK_VEHICLE]:    'action.vehicle.unstuck',
  [ActionType.EXPLODE_VEHICLE]:    'action.vehicle.explode',
  [ActionType.KILL_ENGINE]:        'action.vehicle.killEngine',
  [ActionType.EJECT_DRIVER]:       'action.vehicle.ejectDriver',
  [ActionType.TELEPORT_VEHICLE]:   'action.vehicle.teleport',
  // World
  [ActionType.SET_TIME]:           'action.world.time',
  [ActionType.SET_WEATHER]:        'action.world.weather',
  [ActionType.CLEAR_WEATHER]:      'action.world.sunny',
  [ActionType.WIPE_AI]:            'action.world.wipeAI',
  [ActionType.WIPE_VEHICLES]:      'action.world.wipeVehicles',
  [ActionType.SPAWN_ITEM_WORLD]:   'action.world.spawnItem',
  [ActionType.SET_FOG]:            'action.world.setFog',
  [ActionType.SET_WIND]:           'action.world.setWind',
  [ActionType.FLATTEN_TREES]:      'action.world.flattenTrees',
  [ActionType.CLEAR_ZOMBIES]:      'action.world.clearZombies',
  [ActionType.DELETE_OBJECTS_RADIUS]: 'action.world.deleteObjectsRadius',
  // Spawn
  [ActionType.SPAWN_ZOMBIE]:       'action.spawn.zombie',
  [ActionType.SPAWN_ANIMAL]:       'action.spawn.animal',
  [ActionType.SPAWN_VEHICLE]:      'action.spawn.vehicle',
  [ActionType.SPAWN_BUILDING]:     'action.spawn.building',
  [ActionType.SPAWN_HORDE]:        'action.spawn.horde',
  [ActionType.SPAWN_SUPPLY_CRATE]: 'action.spawn.supplyCrate',
  [ActionType.SPAWN_LOOT_PILE]:    'action.spawn.lootPile',
  [ActionType.SPAWN_ITEM_ATTACHED]: 'action.spawn.itemAttached',
  [ActionType.SPAWN_ITEM_AT]:      'action.spawn.itemAt',
  [ActionType.SPAWN_ZOMBIE_AT]:    'action.spawn.zombieAt',
  [ActionType.SPAWN_ANIMAL_AT]:    'action.spawn.animalAt',
  [ActionType.SPAWN_FIRE]:         'action.spawn.fire',
  [ActionType.SPAWN_SMOKE]:        'action.spawn.smoke',
  [ActionType.SPAWN_HELI_CRASH]:   'action.spawn.heliCrash',
  [ActionType.SPAWN_GAS_ZONE]:     'action.spawn.gasZone',
  // Structure
  [ActionType.OPEN_DOORS]:         'action.structure.openDoors',
  [ActionType.CLOSE_DOORS]:        'action.structure.closeDoors',
  [ActionType.LOOT_MAGNET]:        'action.structure.lootMagnet',
  // Item
  [ActionType.DELETE_ITEM]:        'action.item.delete',
  [ActionType.REPAIR_ITEM]:        'action.item.repair',
  // Config
  [ActionType.RELOAD_CONFIG]:      'action.config.reload',
  // Ban
  [ActionType.UNBAN_PLAYER]:       'action.unban',
});

// ─── Route ↔ ActionType Maps ────────────────────────────
// Used by vehicle and world route handlers to resolve URL params to ActionTypes.

const VEHICLE_ACTION_MAP = Object.freeze({
  'delete':       ActionType.DELETE_VEHICLE,
  'repair':       ActionType.REPAIR_VEHICLE,
  'refuel':       ActionType.REFUEL_VEHICLE,
  'unstuck':      ActionType.UNSTUCK_VEHICLE,
  'explode':      ActionType.EXPLODE_VEHICLE,
  'kill-engine':  ActionType.KILL_ENGINE,
  'eject-driver': ActionType.EJECT_DRIVER,
  'teleport':     ActionType.TELEPORT_VEHICLE,
});

const WORLD_ACTION_MAP = Object.freeze({
  'set-time':             ActionType.SET_TIME,
  'set-weather':          ActionType.SET_WEATHER,
  'sunny':                ActionType.CLEAR_WEATHER,
  'wipe-ai':              ActionType.WIPE_AI,
  'wipe-vehicles':        ActionType.WIPE_VEHICLES,
  'set-fog':              ActionType.SET_FOG,
  'set-wind':             ActionType.SET_WIND,
  'flatten-trees':        ActionType.FLATTEN_TREES,
  'clear-zombies':        ActionType.CLEAR_ZOMBIES,
  'delete-objects-radius': ActionType.DELETE_OBJECTS_RADIUS,
});

const PLAYER_ACTION_MAP = Object.freeze({
  'heal':               ActionType.HEAL_PLAYER,
  'kill':               ActionType.KILL_PLAYER,
  'strip':              ActionType.STRIP_PLAYER,
  'explode':            ActionType.EXPLODE_PLAYER,
  'message':            ActionType.MESSAGE_PLAYER,
  'unstuck':            ActionType.UNSTUCK_PLAYER,
  'freeze':             ActionType.FREEZE_PLAYER,
  'dry':                ActionType.DRY_PLAYER,
  'break-legs':         ActionType.BREAK_LEGS,
  'make-sick':          ActionType.MAKE_SICK,
  'cure':               ActionType.CURE_PLAYER,
  'knockout':           ActionType.KNOCKOUT_PLAYER,
  'wake':               ActionType.WAKE_PLAYER,
  'set-bleeding':       ActionType.SET_BLEEDING,
  'stop-bleeding':      ActionType.STOP_BLEEDING,
  'drop-gear':          ActionType.DROP_GEAR,
  'launch':             ActionType.LAUNCH_PLAYER,
  'ragdoll':            ActionType.RAGDOLL_PLAYER,
  'set-godmode':        ActionType.SET_GODMODE,
  'remove-godmode':     ActionType.REMOVE_GODMODE,
  'set-invisible':      ActionType.SET_INVISIBLE,
  'remove-invisible':   ActionType.REMOVE_INVISIBLE,
  'set-stamina-infinite': ActionType.SET_STAMINA_INFINITE,
  'remove-stamina-infinite': ActionType.REMOVE_STAMINA_INFINITE,
  'respawn':            ActionType.RESPAWN_PLAYER,
  'clear-inventory':    ActionType.CLEAR_INVENTORY,
  'fill-magazines':     ActionType.FILL_MAGAZINES,
});

const SPAWN_ACTION_MAP = Object.freeze({
  'zombie':        ActionType.SPAWN_ZOMBIE,
  'animal':        ActionType.SPAWN_ANIMAL,
  'vehicle':       ActionType.SPAWN_VEHICLE,
  'building':      ActionType.SPAWN_BUILDING,
  'horde':         ActionType.SPAWN_HORDE,
  'supply-crate':  ActionType.SPAWN_SUPPLY_CRATE,
  'loot-pile':     ActionType.SPAWN_LOOT_PILE,
  'item-attached': ActionType.SPAWN_ITEM_ATTACHED,
  'item-at':       ActionType.SPAWN_ITEM_AT,
  'zombie-at':     ActionType.SPAWN_ZOMBIE_AT,
  'animal-at':     ActionType.SPAWN_ANIMAL_AT,
  'fire':          ActionType.SPAWN_FIRE,
  'smoke':         ActionType.SPAWN_SMOKE,
  'heli-crash':    ActionType.SPAWN_HELI_CRASH,
  'gas-zone':      ActionType.SPAWN_GAS_ZONE,
});

module.exports = {
  ActionType,
  LEGACY_SDK_CAPABILITIES,
  INHOUSE_CAPABILITIES,
  RCON_CAPABILITIES,
  ACTION_LABELS,
  AUDIT_CODES,
  VEHICLE_ACTION_MAP,
  WORLD_ACTION_MAP,
  PLAYER_ACTION_MAP,
  SPAWN_ACTION_MAP,
};
