#!/usr/bin/env node
/**
 * First-run setup script.
 * Auto-generates .env with secure defaults if it doesn't exist.
 * Safe to run multiple times — never overwrites existing values.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..', '..');
const ENV_PATH = path.join(ROOT, '.env');
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const DATA_DIR = path.join(ROOT, 'data');

function generateSecret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('hex');
}

function setup() {
  // Ensure data directory exists
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    console.log('[setup] Created data/ directory');
  }

  // If .env already exists, just validate critical fields
  if (fs.existsSync(ENV_PATH)) {
    const existing = fs.readFileSync(ENV_PATH, 'utf-8');

    // Check if JWT_SECRET is still the placeholder
    if (existing.includes('JWT_SECRET=your-super-secret-jwt-key-change-me')) {
      const patched = existing.replace(
        'JWT_SECRET=your-super-secret-jwt-key-change-me',
        `JWT_SECRET=${generateSecret()}`
      );
      fs.writeFileSync(ENV_PATH, patched);
      console.log('[setup] Generated secure JWT_SECRET (was still placeholder)');
    }

    // Check if DISCORD_BOT_API_KEY is the placeholder
    if (existing.includes('DISCORD_BOT_API_KEY=change-this-to-a-random-key')) {
      const patched = fs.readFileSync(ENV_PATH, 'utf-8').replace(
        'DISCORD_BOT_API_KEY=change-this-to-a-random-key',
        `DISCORD_BOT_API_KEY=${generateSecret()}`
      );
      fs.writeFileSync(ENV_PATH, patched);
      console.log('[setup] Generated secure DISCORD_BOT_API_KEY (was still placeholder)');
    }

    console.log('[setup] .env exists — skipping creation');
    return;
  }

  // Generate fresh .env from template
  console.log('[setup] No .env found — generating with secure defaults...');

  const env = `# ─── DayZ Panel Configuration ───────────────────────────
# Auto-generated by setup script

# API Server
PORT=3001
JWT_SECRET=${generateSecret()}

# Default admin — change password on first login via the Setup Wizard
ADMIN_USERNAME=admin
ADMIN_PASSWORD=admin

# DayZ Server (configured via Setup Wizard)
DAYZ_SERVER_IP=127.0.0.1
DAYZ_INSTALL_DIR=

# Discord Integration (optional — configure later)
# DISCORD_BOT_TOKEN=
# DISCORD_CLIENT_ID=
# DISCORD_GUILD_ID=
# DISCORD_ADMIN_ROLE_ID=
# DISCORD_WEBHOOK_URL=
DISCORD_BOT_API_KEY=${generateSecret()}
PANEL_API_URL=http://localhost:3001

# SteamCMD (auto-detected or configured via Setup Wizard)
# STEAMCMD_PATH=
# STEAM_USERNAME=
# STEAM_PASSWORD=

# InHouse Sidecar API (runs alongside your DayZ server)
# Configure per-server via the Servers page (inHouseApiUrl, inHouseApiKey)
# INHOUSE_SIDECAR_PORT=9100
# INHOUSE_API_KEY=${generateSecret(16)}

# CFTools Cloud Integration (DEPRECATED — use InHouse sidecar instead)
# Only needed if you still use CFTools for some servers.
# CFTOOLS_APPLICATION_ID=
# CFTOOLS_SECRET=
`;

  fs.writeFileSync(ENV_PATH, env);
  console.log('[setup] Created .env with secure JWT_SECRET');
  console.log('[setup] Start the panel and complete setup via the web interface');
}

// Run if called directly
if (require.main === module) {
  setup();
}

module.exports = { setup };
